Repository openshift/cluster-api-provider-gcp, pull requests merged in 2019-08, with the labels that each got.

#42 Return errors from scope.Close()
  pkg/cloud/gcp/actuators/machine/actuator.go
  pkg/cloud/gcp/actuators/machine/machine_scope.go
Labels: approved, lgtm, size/S

#43 Add project ID to machine provider spec
  pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
  pkg/cloud/gcp/actuators/machine/machine_scope.go
Labels: approved, lgtm, size/S

#44 Remove special error type when returning to controller
  pkg/cloud/gcp/actuators/machine/actuator.go
Labels: approved, lgtm, size/S

#45 Bump openshift/cluster-api dependencies
  Gopkg.lock
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machine.yaml
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machineset.yaml
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machineset_types.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/sync.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller.go
Labels: approved, lgtm, size/L

#40 Add support for TargetPools
  README.md
  pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
  pkg/apis/gcpprovider/v1beta1/zz_generated.deepcopy.go
  pkg/cloud/gcp/actuators/machine/reconciler.go
  pkg/cloud/gcp/actuators/machine/reconciler_test.go
  pkg/cloud/gcp/actuators/services/compute/computeservice.go
  pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
Labels: approved, lgtm, size/L

#28 Version support
  Gopkg.lock
  cmd/manager/main.go
  pkg/cloud/gcp/actuators/services/compute/computeservice.go
  pkg/version/version.go
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/go.mod
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
Labels: approved, lgtm, size/XXL

#48 bug 1740004: Set additional machine annotations/labels to get pretty machine output
  pkg/cloud/gcp/actuators/machine/reconciler.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#49 Extend makefile with 'make goimports' target
  Makefile
  hack/goimports.sh
Labels: approved, lgtm, size/S

#41 Introduce gosec for security checks
  Makefile
  hack/gosec.sh
Labels: approved, lgtm, size/S

#51 bug 1741765: Allow invalid project/zone machines to be deleted
  Gopkg.lock
  pkg/cloud/gcp/actuators/machine/reconciler.go
  vendor/github.com/openshift/cluster-api/Gopkg.lock
  vendor/github.com/openshift/cluster-api/pkg/controller/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/drain/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/drain/drain.go
  vendor/github.com/openshift/kubernetes-drain/LICENSE
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#57 Label instances created by the actuator with cluster ID
  pkg/cloud/gcp/actuators/machine/reconciler.go
  pkg/cloud/gcp/actuators/machine/reconciler_test.go
Labels: approved, lgtm, size/S
