Repository openshift/cluster-api-provider-gcp, pull requests merged in 2019-09, with the labels that each got.

#58 machine/machine_scope: update status first in Close()
  pkg/cloud/gcp/actuators/machine/machine_scope.go
Labels: approved, lgtm, size/M

#61 Fix 'make goimports' complaint
  pkg/apis/gcpprovider/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XS

#62 Bug 1752088: UPSTREAM: <carry>: openshift: Revendor to bring https://github.com/openshift/cluster-api/pull/72
  go.mod
  go.sum
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL
