Repository openshift/cluster-api-provider-gcp, pull requests merged in 2019-05, with the labels that each got.

#6 Manage status
  pkg/apis/gcpprovider/v1beta1/gcpmachineproviderstatus_types.go
  pkg/apis/gcpprovider/v1beta1/register.go
  pkg/apis/gcpprovider/v1beta1/register_test.go
  pkg/apis/gcpprovider/v1beta1/zz_generated.deepcopy.go
  pkg/cloud/gcp/actuators/machine/actuator.go
  pkg/cloud/gcp/actuators/machine/machine_scope.go
  pkg/cloud/gcp/actuators/machine/reconciler.go
  pkg/cloud/gcp/actuators/machine/reconciler_test.go
  pkg/cloud/gcp/actuators/services/compute/computeservice.go
  pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
Labels: lgtm, size/L

#4 Implement Exists
  pkg/cloud/gcp/actuators/machine/actuator.go
  pkg/cloud/gcp/actuators/machine/reconciler.go
  pkg/cloud/gcp/actuators/machine/reconciler_test.go
  pkg/cloud/gcp/actuators/services/compute/computeservice.go
  pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
Labels: approved, lgtm, size/M

#10 More logging for exists method
  pkg/cloud/gcp/actuators/machine/actuator.go
  pkg/cloud/gcp/actuators/machine/reconciler.go
  pkg/cloud/gcp/actuators/machine/reconciler_test.go
Labels: approved, lgtm, size/S

#11 Implement update
  pkg/cloud/gcp/actuators/machine/actuator.go
  pkg/cloud/gcp/actuators/machine/machine_scope.go
  pkg/cloud/gcp/actuators/machine/reconciler.go
Labels: approved, lgtm, size/M

#9 Implement Delete instance
  pkg/cloud/gcp/actuators/machine/actuator.go
  pkg/cloud/gcp/actuators/machine/reconciler.go
  pkg/cloud/gcp/actuators/machine/reconciler_test.go
  pkg/cloud/gcp/actuators/services/compute/computeservice.go
  pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
Labels: approved, lgtm, size/M

#5 Makefile: drop nested quoting
  Makefile
Labels: approved, lgtm

#13 Fix field
  pkg/cloud/gcp/actuators/machine/machine_scope.go
  pkg/cloud/gcp/actuators/machine/reconciler.go
Labels: approved, lgtm, size/XS

#14 Status conditions
  pkg/apis/gcpprovider/v1beta1/gcpmachineproviderstatus_types.go
  pkg/apis/gcpprovider/v1beta1/zz_generated.deepcopy.go
  pkg/cloud/gcp/actuators/machine/conditions.go
  pkg/cloud/gcp/actuators/machine/conditions_test.go
  pkg/cloud/gcp/actuators/machine/reconciler.go
  pkg/cloud/gcp/actuators/machine/reconciler_test.go
Labels: lgtm, size/L

#20 Update instance internal-dns names
  pkg/cloud/gcp/actuators/machine/reconciler.go
Labels: approved, lgtm, size/S

#23 Convert create into async
  pkg/cloud/gcp/actuators/machine/reconciler.go
Labels: approved, lgtm, size/M

#25 reconciler: change exists to consider TERMINATED state only
  pkg/cloud/gcp/actuators/machine/reconciler.go
Labels: approved, lgtm, size/XS

#24 Make delete async
  pkg/cloud/gcp/actuators/machine/reconciler.go
  pkg/cloud/gcp/actuators/machine/reconciler_test.go
  pkg/cloud/gcp/actuators/services/compute/computeservice.go
  pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
Labels: approved, lgtm, size/M
