Repository openshift/cluster-api-provider-gcp, pull requests merged in 2019-06, with the labels that each got.

#27 Add e2e make test
  Makefile
  hack/e2e.sh
Labels: approved, lgtm, size/S

#17 Implement events
  cmd/manager/main.go
  pkg/cloud/gcp/actuators/machine/actuator.go
  pkg/cloud/gcp/actuators/machine/actuator_test.go
Labels: approved, lgtm, size/M

#29 Switch builds to use Go 1.12
  Dockerfile
  Makefile
  hack/go-fmt.sh
  hack/go-vet.sh
Labels: approved, lgtm, size/XS

#30 Prepend machine.Name to logging
  pkg/cloud/gcp/actuators/machine/actuator.go
  pkg/cloud/gcp/actuators/machine/reconciler.go
Labels: approved, lgtm, size/S
