Repository openshift/cluster-api-provider-gcp, pull requests merged in 2019-07, with the labels that each got.

#31 Update vendor cluster-api and kubernetes-drain
  Gopkg.lock
  vendor/github.com/openshift/cluster-api/Gopkg.lock
  vendor/github.com/openshift/cluster-api/Gopkg.toml
  vendor/github.com/openshift/cluster-api/pkg/controller/add_node.go
  vendor/github.com/openshift/kubernetes-drain/drain.go
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/scheme/scheme.go
Labels: approved, lgtm, size/M

#33 Add namespace flag to controller command
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#34 Fix name of the credentials key
  pkg/cloud/gcp/actuators/machine/machine_scope.go
Labels: approved, lgtm, size/XS

#35 Do not b64-encode user data
  pkg/cloud/gcp/actuators/machine/reconciler.go
Labels: approved, lgtm, size/XS

#36 Allow specifying whether you want a public IP
  pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
  pkg/cloud/gcp/actuators/machine/reconciler.go
Labels: approved, lgtm, size/XS

#37 Pass full URL to image when creating compute instance
  pkg/cloud/gcp/actuators/machine/reconciler.go
  pkg/cloud/gcp/actuators/services/compute/computeservice.go
  pkg/cloud/gcp/actuators/services/compute/computeservice_mock.go
Labels: approved, lgtm, size/S

#39 Use the same type for both internal addresses
  pkg/cloud/gcp/actuators/machine/reconciler.go
Labels: approved, lgtm, size/XS
