Repository openshift/cluster-api-provider-gcp, pull requests merged in 2020-05, with the labels that each got.

#82 Bug 1832186: Bump all dependencies to kube 1.18
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/common_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_types.go
  vendor/k8s.io/utils/exec/README.md
  vendor/k8s.io/utils/pointer/README.md
  vendor/modules.txt
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#88 Bug 1809345: Add the machine's name as a known NodeInternalDNS
  pkg/cloud/gcp/actuators/machine/reconciler.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#89 Bug 1808971: Machine status shows "running" when an instance was terminated
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
