Repository openshift/cluster-api-provider-gcp, pull requests merged in 2020-09, with the labels that each got.

#118 Bug 1872080: Add Dockerfile.rhel to match build configuration in ocp-build-data
  Dockerfile.rhel
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#109 Bug 1733474: Revendor MAO with timeout formatting fix
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, priority/awaiting-more-evidence

#108 Bug 1878170: Add unit tests for machine scope
  pkg/cloud/gcp/actuators/machine/machine_scope_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#114 Bug 1864352: Add leader election mechanism to release 4.5
  cmd/manager/main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
