Repository openshift/cluster-api-provider-gcp, pull requests merged in 2020-07, with the labels that each got.

#99 Add termination handler for spot instances
  Dockerfile
  Makefile
  cmd/termination-handler/main.go
  config/crds/machine.openshift.io.crd.yaml
  pkg/cloud/gcp/actuators/machine/reconciler.go
  pkg/termination/termination.go
  pkg/termination/termination_suite_test.go
  pkg/termination/termination_test.go
Labels: approved, lgtm

#85 [OCPCLOUD-492] Implement leader election for gcp provider
  cmd/manager/main.go
Labels: approved, lgtm, release/4.6

#100 Add spot instance label to machine spec
  pkg/cloud/gcp/actuators/machine/reconciler.go
  pkg/cloud/gcp/actuators/machine/reconciler_test.go
  pkg/termination/termination.go
Labels: approved, lgtm

#94 Enable metrics
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/cloud/gcp/actuators/machine/reconciler.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machineset_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/vsphereprovider/v1beta1/doc.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/vsphereprovider/v1beta1/register.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/vsphereprovider/v1beta1/vsphereproviderconfig_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/vsphereprovider/v1beta1/vsphereproviderstatus_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/vsphereprovider/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/clientset.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/doc.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/doc.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/generated_expansion.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/machine.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/machine_client.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/machinehealthcheck.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/clientset/versioned/typed/machine/v1beta1/machineset.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/informers/externalversions/machine/v1beta1/interface.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/informers/externalversions/machine/v1beta1/machine.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/informers/externalversions/machine/v1beta1/machinehealthcheck.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/informers/externalversions/machine/v1beta1/machineset.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/listers/machine/v1beta1/expansion_generated.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/listers/machine/v1beta1/machine.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/listers/machine/v1beta1/machinehealthcheck.go
  vendor/github.com/openshift/machine-api-operator/pkg/generated/listers/machine/v1beta1/machineset.go
  vendor/github.com/openshift/machine-api-operator/pkg/metrics/metrics.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api-provider-aws/pkg/apis/awsprovider/v1beta1/awsproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/LICENSE
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/azuremachineproviderstatus_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/doc.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/register.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm

#101 support sourceImage outside the existing project
  pkg/cloud/gcp/actuators/machine/reconciler.go
Labels: approved, lgtm

#103 BUG 1856597: Pass scheme to client creation so that it uses scheme with Machine API
  pkg/termination/termination.go
  pkg/termination/termination_suite_test.go
  pkg/termination/termination_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#104 BUG 1858400: [Performance] Lease refresh period for machine-api-controllers is too high, causes heavy writes to etcd at idle
  cmd/manager/main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#106 Bug 1857175: Revendor mao to bring https://github.com/openshift/machine-api-operator/pull/644
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machineset_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
